# Generated by Django 5.1 on 2024-09-14 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='home_header_logos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_src', models.ImageField(upload_to='media/webapp/header_logos/')),
            ],
        ),
        migrations.CreateModel(
            name='qualities_cards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_img', models.ImageField(blank=True, null=True, upload_to='media/webapp/qualities_card/')),
                ('card_title', models.CharField(blank=True, max_length=19, null=True)),
                ('card_des', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='home_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header_heading', models.CharField(blank=True, max_length=60, null=True)),
                ('header_paragraph', models.TextField(blank=True, null=True)),
                ('header_btn_title', models.CharField(blank=True, max_length=25, null=True)),
                ('header_btn_link', models.TextField(blank=True, null=True)),
                ('header_logos', models.ManyToManyField(to='webapp.home_header_logos')),
            ],
        ),
        migrations.CreateModel(
            name='qualities_section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField(blank=True, null=True)),
                ('des', models.TextField(blank=True, null=True)),
                ('domain_count', models.IntegerField(default=20)),
                ('domain_count_des', models.TextField(blank=True, null=True)),
                ('time_duration', models.CharField(blank=True, max_length=30, null=True)),
                ('time_duration_des', models.TextField(blank=True, null=True)),
                ('card', models.ManyToManyField(to='webapp.qualities_cards')),
            ],
        ),
    ]
