# Generated by Django 5.1 on 2024-09-14 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_alter_qualities_cards_card_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='big_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_icon', models.ImageField(upload_to='media/webapp/big_card')),
                ('small_heading', models.TextField(blank=True, null=True)),
                ('heading', models.TextField(blank=True, null=True)),
                ('des', models.TextField(blank=True, null=True)),
                ('img', models.ImageField(upload_to='media/webapp/big_card')),
            ],
        ),
    ]
