# Generated by Django 5.1 on 2024-09-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_big_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='big_card_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/webapp/big_card_card')),
                ('heading', models.CharField(blank=True, max_length=400, null=True)),
                ('des', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('icon', models.ImageField(upload_to='media/webapp/social')),
                ('link', models.TextField()),
            ],
        ),
    ]
