# Generated by Django 5.1 on 2024-09-14 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_big_card_card_social'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_header_of_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(upload_to='media/webapp/about_header')),
                ('heading', models.CharField(max_length=100)),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about_header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.TextField()),
                ('des', models.TextField()),
                ('card', models.ManyToManyField(blank=True, null=True, to='webapp.about_header_of_card')),
            ],
        ),
    ]
