# Generated by Django 5.1 on 2024-09-14 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_about_header_of_card_about_header'),
    ]

    operations = [
        migrations.CreateModel(
            name='about_banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.CharField(max_length=200)),
                ('heading', models.TextField()),
                ('des', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='about_big_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='media/webapp/about/big_card')),
                ('small_heading', models.CharField(max_length=200)),
                ('heading', models.TextField()),
                ('des', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='about_header',
            name='card',
            field=models.ManyToManyField(blank=True, to='webapp.about_header_of_card'),
        ),
    ]
