# Generated by Django 5.1 on 2024-09-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0007_about_banner_about_big_card_alter_about_header_card'),
    ]

    operations = [
        migrations.CreateModel(
            name='job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('job_type', models.CharField(choices=[('on-site', 'On-site'), ('remote', 'Remote'), ('hybrid', 'Hybrid')], default='on-site', max_length=10)),
                ('location', models.CharField(max_length=300)),
                ('role', models.CharField(max_length=300)),
                ('work_time', models.CharField(choices=[('full time', 'Full Time'), ('part time', 'Part Time'), ('on weekend', 'On weekend')], default='full time', max_length=20)),
                ('des', models.TextField(verbose_name='Description')),
                ('requirements', models.TextField()),
            ],
        ),
    ]
