# Generated by Django 5.1 on 2024-09-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_job'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('On-Site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='on-site', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_time',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('On weekend', 'On weekend')], default='full time', max_length=20),
        ),
    ]
