# Generated by Django 5.1 on 2024-09-15 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_alter_job_job_type_alter_job_work_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('On-Site', 'On-site'), ('Remote', 'Remote'), ('Hybrid', 'Hybrid')], default='On-Site', max_length=10),
        ),
        migrations.AlterField(
            model_name='job',
            name='work_time',
            field=models.CharField(choices=[('Full Time', 'Full Time'), ('Part Time', 'Part Time'), ('On weekend', 'On weekend')], default='Full Time', max_length=20),
        ),
    ]
