# Generated by Django 5.1 on 2024-09-15 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0010_job_created_at_alter_job_job_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(upload_to='media/webapp/resumes')),
            ],
        ),
        migrations.CreateModel(
            name='job_application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('company', models.CharField(max_length=500)),
                ('exp', models.CharField(max_length=400)),
                ('current_salary', models.CharField(max_length=16)),
                ('expect_salary', models.CharField(max_length=16)),
                ('note', models.TextField()),
                ('job_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.job')),
                ('resume', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='webapp.resume')),
            ],
        ),
    ]
