# Generated by Django 5.1 on 2024-09-15 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_alter_job_application_job_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='our_contact_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=500)),
                ('phone', models.CharField(max_length=16)),
                ('timings', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=200)),
            ],
        ),
    ]
