# Generated by Django 5.1 on 2024-09-15 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_contact_form_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='project_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=300)),
                ('last_name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=14)),
                ('company', models.CharField(max_length=500)),
                ('region', models.CharField(max_length=400)),
                ('detail', models.TextField()),
                ('consent', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='job_application',
            name='consent',
            field=models.BooleanField(default=True),
        ),
    ]
